-- AWS Free Tier Guardian: Snowflake bootstrap template
-- Status: reference configuration only; not executed by this repository.
-- Run manually only after creating a Snowflake account and reviewing
-- the credit quota, role model, and warehouse settings.

USE ROLE ACCOUNTADMIN;

-- Dedicated transformation role for dbt.
CREATE ROLE IF NOT EXISTS AWS_GUARDIAN_DBT_ROLE;

-- Logical warehouse layout.
CREATE DATABASE IF NOT EXISTS AWS_GUARDIAN;

CREATE SCHEMA IF NOT EXISTS AWS_GUARDIAN.RAW;
CREATE SCHEMA IF NOT EXISTS AWS_GUARDIAN.ANALYTICS;

-- Smallest practical warehouse for a portfolio-scale workload.
-- It starts suspended and stops after 60 seconds of inactivity.
CREATE WAREHOUSE IF NOT EXISTS AWS_GUARDIAN_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Cost-guarded warehouse for AWS Free Tier Guardian dbt transformations';

-- Monthly credit guardrail.
-- Review the quota before running this in a real account.
CREATE RESOURCE MONITOR IF NOT EXISTS AWS_GUARDIAN_MONTHLY_MONITOR
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE AWS_GUARDIAN_XS
  SET RESOURCE_MONITOR = AWS_GUARDIAN_MONTHLY_MONITOR;

-- dbt role permissions.
GRANT USAGE ON WAREHOUSE AWS_GUARDIAN_XS
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

GRANT USAGE ON DATABASE AWS_GUARDIAN
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

GRANT USAGE ON SCHEMA AWS_GUARDIAN.RAW
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

GRANT USAGE ON SCHEMA AWS_GUARDIAN.ANALYTICS
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

-- dbt reads raw scan data.
GRANT SELECT ON ALL TABLES IN SCHEMA AWS_GUARDIAN.RAW
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA AWS_GUARDIAN.RAW
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA AWS_GUARDIAN.RAW
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA AWS_GUARDIAN.RAW
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

-- dbt materialises transformed models here.
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA AWS_GUARDIAN.ANALYTICS
  TO ROLE AWS_GUARDIAN_DBT_ROLE;

-- Later, assign the role to a dedicated dbt service user:
-- GRANT ROLE AWS_GUARDIAN_DBT_ROLE TO USER <DBT_SERVICE_USER>;
